/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchLaterRouteImport } from './routes/watch-later'
import { Route as TrendingRouteImport } from './routes/trending'
import { Route as SearchRouteImport } from './routes/search'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VideoIdRouteImport } from './routes/video.$id'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'

const WatchLaterRoute = WatchLaterRouteImport.update({
  id: '/watch-later',
  path: '/watch-later',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendingRoute = TrendingRouteImport.update({
  id: '/trending',
  path: '/trending',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoIdRoute = VideoIdRouteImport.update({
  id: '/video/$id',
  path: '/video/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/categories': typeof CategoriesRoute
  '/history': typeof HistoryRoute
  '/search': typeof SearchRoute
  '/trending': typeof TrendingRoute
  '/watch-later': typeof WatchLaterRoute
  '/category/$slug': typeof CategorySlugRoute
  '/video/$id': typeof VideoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/categories': typeof CategoriesRoute
  '/history': typeof HistoryRoute
  '/search': typeof SearchRoute
  '/trending': typeof TrendingRoute
  '/watch-later': typeof WatchLaterRoute
  '/category/$slug': typeof CategorySlugRoute
  '/video/$id': typeof VideoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/categories': typeof CategoriesRoute
  '/history': typeof HistoryRoute
  '/search': typeof SearchRoute
  '/trending': typeof TrendingRoute
  '/watch-later': typeof WatchLaterRoute
  '/category/$slug': typeof CategorySlugRoute
  '/video/$id': typeof VideoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/categories'
    | '/history'
    | '/search'
    | '/trending'
    | '/watch-later'
    | '/category/$slug'
    | '/video/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/categories'
    | '/history'
    | '/search'
    | '/trending'
    | '/watch-later'
    | '/category/$slug'
    | '/video/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/categories'
    | '/history'
    | '/search'
    | '/trending'
    | '/watch-later'
    | '/category/$slug'
    | '/video/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CategoriesRoute: typeof CategoriesRoute
  HistoryRoute: typeof HistoryRoute
  SearchRoute: typeof SearchRoute
  TrendingRoute: typeof TrendingRoute
  WatchLaterRoute: typeof WatchLaterRoute
  CategorySlugRoute: typeof CategorySlugRoute
  VideoIdRoute: typeof VideoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watch-later': {
      id: '/watch-later'
      path: '/watch-later'
      fullPath: '/watch-later'
      preLoaderRoute: typeof WatchLaterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trending': {
      id: '/trending'
      path: '/trending'
      fullPath: '/trending'
      preLoaderRoute: typeof TrendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video/$id': {
      id: '/video/$id'
      path: '/video/$id'
      fullPath: '/video/$id'
      preLoaderRoute: typeof VideoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CategoriesRoute: CategoriesRoute,
  HistoryRoute: HistoryRoute,
  SearchRoute: SearchRoute,
  TrendingRoute: TrendingRoute,
  WatchLaterRoute: WatchLaterRoute,
  CategorySlugRoute: CategorySlugRoute,
  VideoIdRoute: VideoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
